spring:
  main:
    allow-circular-references: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/ddb1
    username: postgres
    password: 112233qq
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
  flyway:
    baseline-on-migrate: true



